name: Build and deploy

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: false
        default: 'develop'
        type: choice
        options:
          - develop
          - staging
          - production

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Declare variables
        id: variables
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=hash::$(git rev-parse --short HEAD)"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v2
        with:
          context: backend
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USER_NAME }}/todo-app:latest,
            ${{ secrets.DOCKER_HUB_USER_NAME }}/todo-app:${{ steps.variables.outputs.hash }}

      - name: Pull image and run container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.API_HOST }}
          username: ${{ secrets.API_HOST_USERNAME }}
          key: ${{ secrets.API_HOST_PRIVATE_KEY }}
          script: |
            docker stop todo-app-api; \
            docker run --rm --detach \
            --env VERSION=${{ steps.variables.outputs.hash }} \
            --env MONGODB_URL=${{ secrets.MONGODB_URL }} \
            --name=todo-app-api \
            --network=todo-app-network \
            --publish=8000:8000 \
            --workdir=/app \
            lecovich/todo-app:${{ steps.variables.outputs.hash }} \
            poetry run uvicorn app:app --host=0.0.0.0 --port=8000

  build_frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Packages
        working-directory: frontend
        run: |
          npm install --global yarn && \
          yarn install && \
          yarn build

      - name: Copy to bucket
        uses: zdurham/s3-upload-github-action@master
        with:
          args: --endpoint-url=https://storage.yandexcloud.net --recursive
        env:
          S3_BUCKET: nlesnykh-test-bucket
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_KEY: 'todo-app-static/'
          FILE: 'frontend/build/'
